[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
coop_meme = "DU8dTxb7qED4fNHmZkDD5Nz6eM6K335x5dczK7FqJRv5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
